# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestration.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'orchestration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13orchestration.proto\"\x13\n\x11\x43heckReadyRequest\"&\n\x12\x43heckReadyResponse\x12\x10\n\x08is_ready\x18\x01 \x01(\x08\"\x1c\n\x0bKillRequest\x12\r\n\x05\x61\x62ort\x18\x01 \x01(\x08\"\x0e\n\x0cKillResponse\"<\n\x1aWorkerConfigurationRequest\x12\x0c\n\x04port\x18\x01 \x01(\x05\x12\x10\n\x08topology\x18\x02 \x03(\t\"\x1d\n\x1bWorkerConfigurationResponse2\xc1\x01\n\x0bWorkerAgent\x12R\n\x13\x43onfigurationChange\x12\x1b.WorkerConfigurationRequest\x1a\x1c.WorkerConfigurationResponse\"\x00\x12\x37\n\nCheckReady\x12\x12.CheckReadyRequest\x1a\x13.CheckReadyResponse\"\x00\x12%\n\x04Kill\x12\x0c.KillRequest\x1a\r.KillResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKREADYREQUEST']._serialized_start=23
  _globals['_CHECKREADYREQUEST']._serialized_end=42
  _globals['_CHECKREADYRESPONSE']._serialized_start=44
  _globals['_CHECKREADYRESPONSE']._serialized_end=82
  _globals['_KILLREQUEST']._serialized_start=84
  _globals['_KILLREQUEST']._serialized_end=112
  _globals['_KILLRESPONSE']._serialized_start=114
  _globals['_KILLRESPONSE']._serialized_end=128
  _globals['_WORKERCONFIGURATIONREQUEST']._serialized_start=130
  _globals['_WORKERCONFIGURATIONREQUEST']._serialized_end=190
  _globals['_WORKERCONFIGURATIONRESPONSE']._serialized_start=192
  _globals['_WORKERCONFIGURATIONRESPONSE']._serialized_end=221
  _globals['_WORKERAGENT']._serialized_start=224
  _globals['_WORKERAGENT']._serialized_end=417
# @@protoc_insertion_point(module_scope)
